---
- name: Configure EC2 for DevOps tasks
  hosts: all
  become: true

  vars:
    devops_group: devops
    app_user: ubuntu

  tasks:

    # ---------------------------
    # Ensure devops group exists
    # ---------------------------
    - name: Create devops group
      ansible.builtin.group:
        name: "{{ devops_group }}"
        state: present

    # ---------------------------
    # Copy sample config file
    # ---------------------------
    - name: Copy config.txt to /opt/
      ansible.builtin.copy:
        src: files/config.txt
        dest: /opt/config.txt
        owner: "{{ app_user }}"
        group: "{{ devops_group }}"
        mode: '0660'

    # ---------------------------
    # Install PostgreSQL
    # ---------------------------
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: latest
        update_cache: yes

    - name: Ensure PostgreSQL service is enabled and running
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    # ---------------------------
    # Install and configure web server (Nginx)
    # ---------------------------
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure Nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    # ---------------------------
    # Install Docker
    # ---------------------------
    - name: Install prerequisites for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ app_user }}"
        groups: docker
        append: yes

    # ---------------------------
    # Install Docker Compose
    # ---------------------------
    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'


    # ---------------------------
    # Deploy monitoring stack via Docker Compose
    # ---------------------------
    - name: Create monitoring directory
      ansible.builtin.file:
        path: /opt/monitoring
        state: directory
        owner: "{{ app_user }}"
        group: "{{ devops_group }}"
        mode: '0755'

    - name: Copy monitoring Docker Compose file
      ansible.builtin.copy:
        src: files/monitoring/docker-compose.yml
        dest: /opt/monitoring/docker-compose.yml
        owner: "{{ app_user }}"
        group: "{{ devops_group }}"
        mode: '0644'

    - name: Copy Prometheus configuration file
      ansible.builtin.copy:
        src: files/monitoring/prometheus.yml
        dest: /opt/monitoring/prometheus.yml
        owner: "{{ app_user }}"
        group: "{{ devops_group }}"
        mode: '0644'

    - name: Copy monitoring env file
      ansible.builtin.copy:
        src: files/monitoring/.env
        dest: /opt/monitoring/.env
        owner: "{{ app_user }}"
        group: "{{ devops_group }}"
        mode: '0600'

    - name: Deploy monitoring containers
      ansible.builtin.command: docker-compose -f /opt/monitoring/docker-compose.yml up -d
      args:
        chdir: /opt/monitoring
