services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - .env        # Load variables from .env file
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
